import React, { useEffect, useMemo, useState } from "react";
import { Link, NavLink, Navigate, Route, Routes, useLocation } from "react-router-dom";
import { Activity, BellRing, Check, CheckCircle2, ChevronRight, CircleUserRound, ClipboardList, Clock3, Mail, ShieldAlert, ShieldCheck, UsersRound } from "lucide-react";
import { initialState, type State } from "./domain";
import "./advisor-enhancements.css";

type ReviewItem={id:string;client:string;initials:string;type:"Planning Update"|"Assessment"|"Follow-up";reason:string;date:string;priority:"High"|"Standard";resolved:boolean};
type Engagement={id:string;client:string;activity:string;type:"Planning"|"Assessment"|"Education"|"Checklist"|"Profile";time:string};
type Outstanding={id:string;client:string;activity:string;due:string;followUp:string;overdue?:boolean};
type Communication={id:string;client:string;subject:string;status:"Scheduled"|"Sent"|"Escalated";date:string};
type AdvisorDemo={resolved:string[];communications:Communication[]};
const advisorKey="retirementtrack-advisor-v1";
const learningTitles=["What does your next chapter look like?","Making the most of your planning check-in","Putting investment risk into perspective","A practical introduction to required distributions","Your age 65 planning conversation","Five retirement facts worth revisiting"];
const defaultAdvisor:AdvisorDemo={resolved:[],communications:[
  {id:"message-1",client:"Sarah Smith",subject:"Planning Update reminder",status:"Scheduled",date:"September 23"},
  {id:"message-2",client:"Martin Cole",subject:"Assessment reminder",status:"Sent",date:"Yesterday"},
  {id:"message-3",client:"Ana Morales",subject:"Overdue Planning Update follow-up",status:"Escalated",date:"September 8"},
]};
const nav=[["dashboard","Advisor dashboard",Activity],["attention","Needs attention",ShieldAlert],["planning","Planning Updates",ClipboardList],["assessments","Assessments",ShieldCheck],["follow-ups","Follow-up / review",CheckCircle2],["communications","Communications",Mail],["activity","Client activity",Clock3],["clients","Client list",UsersRound]] as const;

function readClient():State{try{const saved=JSON.parse(localStorage.getItem("retirementtrack-demo-v1")||"null");return saved?.version===1?saved:initialState()}catch{return initialState()}}
function clientExceptions(state:State):ReviewItem[]{const rows:ReviewItem[]=[];if(state.planning.status==="Completed"&&state.planning.changes.length)rows.push({id:"sarah-planning",client:"Sarah Smith",initials:"SS",type:"Planning Update",reason:`${state.planning.changes.length} meaningful change${state.planning.changes.length>1?"s":""} detected`,date:"Today",priority:"High",resolved:false});if(state.assessment.status==="Completed"&&state.exceptions.some(x=>x.sourceId===state.assessment.id))rows.push({id:"sarah-assessment",client:"Sarah Smith",initials:"SS",type:"Assessment",reason:`Investment & Risk Assessment: ${state.assessment.result} meets the illustrative review rule`,date:"Today",priority:"Standard",resolved:false});return rows}
function staticExceptions():ReviewItem[]{return[
  {id:"elise-follow",client:"Elise Robinson",initials:"ER",type:"Follow-up",reason:"Retirement timeline changed from 67 to 65",date:"Yesterday",priority:"High",resolved:false},
  {id:"martin-assessment",client:"Martin Cole",initials:"MC",type:"Assessment",reason:"Client requested a conversation about the assessment result",date:"Sep 7",priority:"Standard",resolved:false},
  {id:"ana-planning",client:"Ana Morales",initials:"AM",type:"Planning Update",reason:"Planning Update passed the illustrative overdue threshold",date:"Sep 3",priority:"Standard",resolved:false},
]}
function accomplishments(state:State):Engagement[]{const rows:Engagement[]=[];if(state.profileComplete)rows.push({id:"sarah-profile",client:"Sarah Smith",activity:"Completed minimum profile",type:"Profile",time:"Today"});if(state.planning.status==="Completed")rows.push({id:"sarah-update",client:"Sarah Smith",activity:state.planning.changes.length?"Completed Planning Update":"Completed Planning Update · no material changes",type:"Planning",time:"Today"});if(state.assessment.status==="Completed")rows.push({id:"sarah-assessment-complete",client:"Sarah Smith",activity:`Completed Investment & Risk Assessment · ${state.assessment.result}`,type:"Assessment",time:"Today"});state.read.forEach(id=>{const title=learningTitles[Number(id)];if(title)rows.push({id:`sarah-learning-${id}`,client:"Sarah Smith",activity:`Completed “${title}”`,type:"Education",time:"Today"})});return[...rows,{id:"elise-checklist",client:"Elise Robinson",activity:"Completed Retirement Preparedness Checklist",type:"Checklist",time:"Yesterday"},{id:"martin-rmd",client:"Martin Cole",activity:"Explored RMD education",type:"Education",time:"Sep 7"}]}
function buildOutstanding(state:State):Outstanding[]{const rows:Outstanding[]=[];if(state.planning.status==="Due")rows.push({id:"sarah-update-due",client:"Sarah Smith",activity:"Quarterly Planning Update",due:"Due September 30",followUp:"Reminder scheduled September 23"});if(state.assessment.status!=="Completed")rows.push({id:"sarah-assessment-open",client:"Sarah Smith",activity:"Investment & Risk Assessment",due:"Recommended",followUp:"RetirementTrack will follow up"});return[...rows,{id:"elise-checklist-open",client:"Elise Robinson",activity:"Medicare readiness checklist",due:"Due in 12 days",followUp:"Reminder scheduled"},{id:"ana-update-overdue",client:"Ana Morales",activity:"Planning Update",due:"Overdue 7 days",followUp:"Escalated after reminder sequence",overdue:true}]}
function useAdvisorState(){const[demo,setDemo]=useState<AdvisorDemo>(()=>{try{const saved=JSON.parse(localStorage.getItem(advisorKey)||"null");return{...defaultAdvisor,resolved:Array.isArray(saved?.resolved)?saved.resolved:[]}}catch{return defaultAdvisor}});const[client,setClient]=useState<State>(readClient);useEffect(()=>localStorage.setItem(advisorKey,JSON.stringify(demo)),[demo]);const refresh=()=>setClient(readClient());const items=useMemo(()=>[...clientExceptions(client),...staticExceptions()].map(x=>({...x,resolved:demo.resolved.includes(x.id)})),[client,demo.resolved]);const engagement=useMemo(()=>accomplishments(client),[client]);const outstanding=useMemo(()=>buildOutstanding(client),[client]);return{demo,setDemo,client,items,engagement,outstanding,refresh}}
type Workspace=ReturnType<typeof useAdvisorState>;

function AdvisorHeader({eyebrow,title,children}:{eyebrow:string;title:string;children?:React.ReactNode}){return <header className="advisor-heading"><p>{eyebrow}</p><h1 tabIndex={-1}>{title}</h1>{children&&<div>{children}</div>}</header>}
export function AdvisorWorkspace(){const state=useAdvisorState();const location=useLocation();useEffect(()=>{state.refresh();document.querySelector<HTMLHeadingElement>("h1")?.focus();window.scrollTo(0,0)},[location.pathname]);const label=nav.find(([path])=>location.pathname.includes(path))?.[1]||"Advisor dashboard";const count=state.items.filter(x=>!x.resolved).length;return <div className="advisor-app"><a className="skip" href="#advisor-main">Skip to advisor content</a><aside className="advisor-sidebar"><Link to="/advisor/dashboard" className="advisor-brand"><Activity size={27}/><span>RetirementTrack<small>ADVISOR WORKSPACE</small></span></Link><p>MICHAEL CARTER, CFP®</p><nav aria-label="Advisor navigation">{nav.map(([path,title,Icon])=><NavLink key={path} to={`/advisor/${path}`}><Icon size={18}/><span>{title}</span>{path==="attention"&&count>0&&<i>{count}</i>}</NavLink>)}</nav><div className="advisor-sidebar-foot"><CircleUserRound size={18}/><span>Harbor Wealth<br/>84 assigned clients</span><Link to="/client/dashboard">View client portal <ChevronRight size={14}/></Link></div></aside><section className="advisor-workspace"><div className="advisor-topbar"><span>Advisor workspace <ChevronRight size={14}/> <strong>{label}</strong></span><div><span className="demo-pill">DISCOVERY PROTOTYPE</span><button aria-label="Refresh local client activity" className="advisor-refresh" onClick={state.refresh}>Refresh</button><span className="advisor-avatar">MC</span></div></div><main id="advisor-main" className="advisor-main"><Routes><Route path="dashboard" element={<Dashboard {...state}/>}/><Route path="attention" element={<Attention {...state}/>}/><Route path="planning" element={<PlanningQueue {...state}/>}/><Route path="assessments" element={<AssessmentQueue {...state}/>}/><Route path="follow-ups" element={<FollowUps {...state}/>}/><Route path="communications" element={<Communications {...state}/>}/><Route path="activity" element={<RecentActivity {...state}/>}/><Route path="clients" element={<ClientList {...state}/>}/><Route path="*" element={<Navigate to="dashboard" replace/>}/></Routes></main></section></div>}
function resolveItem(setDemo:React.Dispatch<React.SetStateAction<AdvisorDemo>>,id:string){setDemo(s=>({...s,resolved:s.resolved.includes(id)?s.resolved:[...s.resolved,id]}))}
function ReviewCard({item,resolve}:{item:ReviewItem;resolve:(id:string)=>void}){return <article className={`advisor-review ${item.resolved?"is-resolved":""}`}><div className="advisor-initials">{item.initials}</div><div className="advisor-review-main"><div><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority}</span><span className="review-type">Exception · {item.type}</span></div><h3>{item.client}</h3><p>{item.reason}</p><small>{item.date}</small></div><div className="advisor-review-action">{item.resolved?<span><Check size={15}/> Resolved</span>:<button className="button secondary" onClick={()=>resolve(item.id)}>Review exception <ChevronRight size={15}/></button>}</div></article>}
function ActivityRows({events,limit}:{events:Engagement[];limit?:number}){return <section className="activity-rows">{events.slice(0,limit).map(x=><div key={x.id}><Activity size={17}/><div><strong>{x.client} · {x.activity}</strong><small>{x.type} · No action needed</small></div><span>{x.time}</span></div>)}</section>}
function OutstandingRows({items,limit}:{items:Outstanding[];limit?:number}){return <section className="advisor-outstanding-list">{items.slice(0,limit).map(x=><article key={x.id} className={x.overdue?"is-overdue":""}><Clock3 size={18}/><div><strong>{x.client} · {x.activity}</strong><span>{x.due}</span><small>{x.followUp}</small></div><em>{x.overdue?"Exception":"Platform follow-up"}</em></article>)}</section>}

function Dashboard({items,setDemo,engagement,outstanding,refresh}:Workspace){const open=items.filter(x=>!x.resolved);return <><AdvisorHeader eyebrow="CLIENT VISIBILITY · EXCEPTION-BASED SUPPORT" title="Good morning, Michael.">See client progress, outstanding activities, and the exceptions where your guidance may help.</AdvisorHeader><section className="advisor-summary advisor-summary-philosophy"><div><span>Client accomplishments</span><strong>{engagement.length}</strong><small>Recent learning and actions</small></div><div><span>Outstanding</span><strong>{outstanding.length}</strong><small>Platform-managed follow-up</small></div><div><span>Needs attention</span><strong>{open.length}</strong><small>Advisor exceptions</small></div><div><span>Assigned clients</span><strong>84</strong><small>Visible client journeys</small></div></section><section className="advisor-operating-note"><BellRing size={20}/><div><strong>RetirementTrack handles routine guidance and reminders.</strong><span>You maintain visibility and step in when a client asks or an approved exception rule is met.</span></div></section><div className="advisor-layout"><section><div className="advisor-section-title"><div><p>CLIENT ENGAGEMENT</p><h2>Recent accomplishments</h2></div><Link to="/advisor/activity">View all activity <ChevronRight size={15}/></Link></div><ActivityRows events={engagement} limit={4}/><div className="advisor-section-title split"><div><p>EXCEPTION-BASED SUPPORT</p><h2>Needs advisor attention</h2></div><Link to="/advisor/attention">View all <ChevronRight size={15}/></Link></div><div className="advisor-list">{open.slice(0,3).map(x=><ReviewCard key={x.id} item={x} resolve={id=>resolveItem(setDemo,id)}/>)}</div></section><aside className="advisor-rail"><section className="advisor-rail-card"><p>IMPORTANT OUTSTANDING</p><h2>{outstanding.length} client activities</h2><span>Routine follow-up remains with RetirementTrack until an exception threshold is reached.</span><Link to="/advisor/planning">Review outstanding <ChevronRight size={15}/></Link></section><section className="advisor-rail-card"><p>AUTOMATED FOLLOW-UP</p><h2>2 reminders active</h2><span>One reminder is scheduled and one was recently sent. No advisor action is required.</span><Link to="/advisor/communications">View reminder activity <ChevronRight size={15}/></Link></section><section className="advisor-rail-card advisor-client-count"><UsersRound size={22}/><h2>84 assigned clients</h2><span>Open a client journey to see accomplishments, upcoming work, and exceptions together.</span><Link to="/advisor/clients">Open client list <ChevronRight size={15}/></Link></section></aside></div><button className="advisor-sync" onClick={refresh}>Refresh local client-demo activity</button></>}
function Attention({items,setDemo}:Workspace){const open=items.filter(x=>!x.resolved);return <><AdvisorHeader eyebrow="NEEDS ATTENTION" title="Exceptions, with a clear reason.">Only client requests, meaningful changes, approved review conditions, and sufficiently overdue activity appear here.</AdvisorHeader><section className="advisor-filter"><span>{open.length} open advisor exceptions</span><button className="button secondary" onClick={()=>setDemo(s=>({...s,resolved:[]}))}>Restore demo queue</button></section><div className="advisor-list wide">{open.length?open.map(x=><ReviewCard key={x.id} item={x} resolve={id=>resolveItem(setDemo,id)}/>):<div className="advisor-empty"><CheckCircle2/><h2>You are up to date.</h2><p>No client exceptions require attention.</p></div>}</div></>}
function PlanningQueue({items,setDemo,client,outstanding}:Workspace){const exceptions=items.filter(x=>x.type==="Planning Update"&&!x.resolved);const routine=outstanding.filter(x=>x.activity.includes("Planning Update"));return <><AdvisorHeader eyebrow="RECURRING CLIENT UPDATES" title="Planning Updates">See routine status separately from updates that require professional review.</AdvisorHeader><section className="advisor-section-title"><div><p>PLATFORM-MANAGED</p><h2>Outstanding updates</h2></div></section><OutstandingRows items={routine}/><section className="advisor-section-title split"><div><p>ADVISOR ATTENTION</p><h2>Meaningful changes and overdue exceptions</h2></div></section><section className="advisor-context"><ClipboardList/><span>{client.planning.status==="Completed"?(client.planning.changes.length?`Sarah submitted an update with ${client.planning.changes.length} meaningful change(s).`:"Sarah submitted an update with no material changes; no advisor task was created."):"Sarah’s update is due September 30. RetirementTrack will send the routine reminder."}</span></section><div className="advisor-list wide">{exceptions.map(x=><ReviewCard key={x.id} item={x} resolve={id=>resolveItem(setDemo,id)}/>)}</div></>}
function AssessmentQueue({items,setDemo,client,outstanding}:Workspace){const exceptions=items.filter(x=>x.type==="Assessment"&&!x.resolved);const routine=outstanding.filter(x=>x.activity.includes("Assessment"));return <><AdvisorHeader eyebrow="ASSESSMENT VISIBILITY" title="Assessments">Completion is visible; advisor work appears only when an approved rule or client request applies.</AdvisorHeader><OutstandingRows items={routine}/><section className="advisor-context"><ShieldCheck/><span>{client.assessment.status==="Completed"?`Sarah completed the assessment with a ${client.assessment.result} result.`:"Sarah’s assessment remains available. RetirementTrack will provide routine follow-up."}</span></section><div className="advisor-list wide">{exceptions.map(x=><ReviewCard key={x.id} item={x} resolve={id=>resolveItem(setDemo,id)}/>)}</div></>}
function FollowUps({items,setDemo}:Workspace){const rows=items.filter(x=>x.type==="Follow-up"&&!x.resolved);return <><AdvisorHeader eyebrow="ACTIVE CONVERSATIONS" title="Follow-up / review">Focused next steps initiated by a client or created from an approved exception.</AdvisorHeader><div className="advisor-list wide">{rows.map(x=><ReviewCard key={x.id} item={x} resolve={id=>resolveItem(setDemo,id)}/>)}</div></>}
function Communications({demo}:Workspace){return <><AdvisorHeader eyebrow="AUTOMATED COMMUNICATION VISIBILITY" title="Reminder activity">RetirementTrack handles routine reminders. You retain visibility without routine approval work.</AdvisorHeader><section className="advisor-list wide">{demo.communications.map(x=><article className="advisor-review advisor-communication" key={x.id}><div className="advisor-initials"><BellRing size={17}/></div><div className="advisor-review-main"><span className={`communication-status status-${x.status.toLowerCase()}`}>{x.status}</span><h3>{x.client}</h3><p>{x.subject}</p><small>{x.date}</small></div><div className="advisor-review-action"><span>{x.status==="Escalated"?<><ShieldAlert size={15}/> Advisor visibility</>:<><Check size={15}/> No action needed</>}</span></div></article>)}</section><section className="advisor-context"><Mail/><span>Delivery channels, consent rules, templates, and production scheduling remain future implementation decisions.</span></section></>}
function RecentActivity({engagement}:Workspace){return <><AdvisorHeader eyebrow="CLIENT ENGAGEMENT" title="Client accomplishments">See what clients have completed, reviewed, or explored. These records provide context without automatically creating work.</AdvisorHeader><ActivityRows events={engagement}/></>}
function ClientList({items,client,engagement,outstanding}:Workspace){const[selected,setSelected]=useState("Sarah Smith");const clients=[{name:"Sarah Smith",stage:"Approaching retirement",status:items.some(x=>x.client==="Sarah Smith"&&!x.resolved)?"Needs attention":"Current",last:"Today"},{name:"Elise Robinson",stage:"Approaching retirement",status:"Current",last:"Yesterday"},{name:"Martin Cole",stage:"Building toward retirement",status:"Client requested contact",last:"Sep 7"},{name:"Ana Morales",stage:"Already retired",status:"Overdue exception",last:"Sep 3"}];const current=clients.find(x=>x.name===selected)||clients[0];const isSarah=selected==="Sarah Smith";const done=engagement.filter(x=>x.client===selected).length;const remaining=outstanding.filter(x=>x.client===selected).length;const exceptions=items.filter(x=>x.client===selected&&!x.resolved).length;return <><AdvisorHeader eyebrow="ASSIGNED CLIENTS" title="Client journeys">Select a client to see progress, outstanding activity, and exceptions together.</AdvisorHeader><div className="advisor-client-layout"><section className="advisor-client-table"><div className="advisor-client-head"><span>Client</span><span>Life stage</span><span>Current state</span><span>Last activity</span></div>{clients.map(x=><button type="button" className={`advisor-client-row ${selected===x.name?"selected":""}`} key={x.name} onClick={()=>setSelected(x.name)}><span className="client-name"><span className="advisor-initials small">{x.name.split(" ").map(p=>p[0]).join("")}</span><strong>{x.name}</strong></span><span>{x.stage}</span><span>{x.status}</span><span>{x.last}</span></button>)}</section><aside className="advisor-client-journey"><p>CLIENT JOURNEY</p><h2>{current.name}</h2><span>{current.stage}</span><div className="journey-metric"><strong>{isSarah?done:2}</strong><span>Recent accomplishments</span></div><div className="journey-metric"><strong>{remaining}</strong><span>Outstanding activities</span></div><div className="journey-metric"><strong>{exceptions}</strong><span>Open exceptions</span></div>{isSarah&&<div className="journey-detail"><small>LATEST CONTEXT</small><span>Planning Update: {client.planning.status}</span><span>Assessment: {client.assessment.status}</span><span>Learning resources completed: {client.read.length}</span></div>}<Link to="/advisor/activity">View engagement history <ChevronRight size={15}/></Link></aside></div></>}
