import React, { useEffect, useMemo, useState } from "react";
import { Link, NavLink, Navigate, Route, Routes, useLocation } from "react-router-dom";
import { Activity, BellRing, Check, CheckCircle2, ChevronRight, CircleUserRound, ClipboardList, Clock3, Mail, ShieldAlert, ShieldCheck, UsersRound } from "lucide-react";
import { initialState, type State } from "./domain";

type ReviewItem = { id: string; client: string; initials: string; type: "Planning Update" | "Assessment" | "Follow-up"; reason: string; date: string; priority: "High" | "Standard"; resolved: boolean };
type AdvisorDemo = { resolved: string[]; communications: { id: string; client: string; subject: string; status: "Approval needed" | "Ready"; date: string }[] };
const advisorKey = "retirementtrack-advisor-v1";
const defaultAdvisor: AdvisorDemo = { resolved: [], communications: [{ id: "message-1", client: "Elise Robinson", subject: "Planning Update reminder", status: "Approval needed", date: "Today" }, { id: "message-2", client: "Martin Cole", subject: "Assessment reminder", status: "Ready", date: "Yesterday" }] };
const nav = [["dashboard", "Advisor dashboard", Activity], ["attention", "Needs attention", ShieldAlert], ["planning", "Planning Updates", ClipboardList], ["assessments", "Assessments", ShieldCheck], ["follow-ups", "Follow-up / review", CheckCircle2], ["communications", "Communications", Mail], ["activity", "Recent activity", Clock3], ["clients", "Client list", UsersRound]] as const;

function readClient(): State { try { const saved = JSON.parse(localStorage.getItem("retirementtrack-demo-v1") || "null"); return saved?.version === 1 ? saved : initialState(); } catch { return initialState(); } }
function clientItems(state: State): ReviewItem[] {
  const entries: ReviewItem[] = [];
  if (state.planning.status === "Completed" && state.planning.changes.length) entries.push({ id: "sarah-planning", client: "Sarah Smith", initials: "SS", type: "Planning Update", reason: `${state.planning.changes.length} meaningful change${state.planning.changes.length > 1 ? "s" : ""} detected`, date: "Today", priority: "High", resolved: false });
  if (state.assessment.status === "Completed") entries.push({ id: "sarah-assessment", client: "Sarah Smith", initials: "SS", type: "Assessment", reason: `Investment & Risk Assessment: ${state.assessment.result}`, date: "Today", priority: "Standard", resolved: false });
  if (state.planning.status === "Due") entries.push({ id: "sarah-due", client: "Sarah Smith", initials: "SS", type: "Planning Update", reason: "Quarterly update due September 30", date: "Due in 21 days", priority: "Standard", resolved: false });
  return entries;
}
function staticItems(): ReviewItem[] { return [{ id: "elise-follow", client: "Elise Robinson", initials: "ER", type: "Follow-up", reason: "Retirement timeline changed from 67 to 65", date: "Yesterday", priority: "High", resolved: false }, { id: "martin-assessment", client: "Martin Cole", initials: "MC", type: "Assessment", reason: "Assessment review requested", date: "Sep 7", priority: "Standard", resolved: false }, { id: "ana-planning", client: "Ana Morales", initials: "AM", type: "Planning Update", reason: "Planning Update overdue", date: "Sep 3", priority: "Standard", resolved: false }]; }
function useAdvisorState() { const [demo, setDemo] = useState<AdvisorDemo>(() => { try { return { ...defaultAdvisor, ...JSON.parse(localStorage.getItem(advisorKey) || "null") }; } catch { return defaultAdvisor; } }); const [client, setClient] = useState<State>(readClient); useEffect(() => { localStorage.setItem(advisorKey, JSON.stringify(demo)); }, [demo]); const refresh = () => setClient(readClient()); const items = useMemo(() => [...clientItems(client), ...staticItems()].map(x => ({ ...x, resolved: demo.resolved.includes(x.id) })), [client, demo.resolved]); return { demo, setDemo, client, items, refresh }; }
function AdvisorHeader({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <header className="advisor-heading"><p>{eyebrow}</p><h1 tabIndex={-1}>{title}</h1>{children && <div>{children}</div>}</header>; }

export function AdvisorWorkspace() { const state = useAdvisorState(); const location = useLocation(); useEffect(() => { state.refresh(); document.querySelector<HTMLHeadingElement>("h1")?.focus(); window.scrollTo(0, 0); }, [location.pathname]); const label = nav.find(([path]) => location.pathname.includes(path))?.[1] || "Advisor dashboard"; return <div className="advisor-app"><a className="skip" href="#advisor-main">Skip to advisor content</a><aside className="advisor-sidebar"><Link to="/advisor/dashboard" className="advisor-brand"><Activity size={27}/><span>RetirementTrack<small>ADVISOR WORKSPACE</small></span></Link><p>MICHAEL CARTER, CFP®</p><nav aria-label="Advisor navigation">{nav.map(([path, title, Icon]) => <NavLink key={path} to={`/advisor/${path}`}><Icon size={18}/><span>{title}</span>{path === "attention" && state.items.filter(x => !x.resolved).length > 0 && <i>{state.items.filter(x => !x.resolved).length}</i>}</NavLink>)}</nav><div className="advisor-sidebar-foot"><CircleUserRound size={18}/><span>Harbor Wealth<br/>84 assigned clients</span><Link to="/client/dashboard">View client portal <ChevronRight size={14}/></Link></div></aside><section className="advisor-workspace"><div className="advisor-topbar"><span>Advisor workspace <ChevronRight size={14}/> <strong>{label}</strong></span><div><span className="demo-pill">DISCOVERY PROTOTYPE</span><button aria-label="Refresh local client activity" className="advisor-refresh" onClick={state.refresh}>Refresh</button><span className="advisor-avatar">MC</span></div></div><main id="advisor-main" className="advisor-main"><Routes><Route path="dashboard" element={<Dashboard {...state}/>}/><Route path="attention" element={<Attention {...state}/>}/><Route path="planning" element={<PlanningQueue {...state}/>}/><Route path="assessments" element={<AssessmentQueue {...state}/>}/><Route path="follow-ups" element={<FollowUps {...state}/>}/><Route path="communications" element={<Communications {...state}/>}/><Route path="activity" element={<RecentActivity {...state}/>}/><Route path="clients" element={<ClientList {...state}/>}/><Route path="*" element={<Navigate to="dashboard" replace/>}/></Routes></main></section></div>; }

type Workspace = ReturnType<typeof useAdvisorState>;
function resolveItem(setDemo: React.Dispatch<React.SetStateAction<AdvisorDemo>>, id: string) { setDemo(s => ({ ...s, resolved: s.resolved.includes(id) ? s.resolved : [...s.resolved, id] })); }
function ReviewCard({ item, resolve }: { item: ReviewItem; resolve: (id: string) => void }) { return <article className={`advisor-review ${item.resolved ? "is-resolved" : ""}`}><div className="advisor-initials">{item.initials}</div><div className="advisor-review-main"><div><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority}</span><span className="review-type">{item.type}</span></div><h3>{item.client}</h3><p>{item.reason}</p><small>{item.date}</small></div><div className="advisor-review-action">{item.resolved ? <span><Check size={15}/> Resolved</span> : <button className="button secondary" onClick={() => resolve(item.id)}>Review <ChevronRight size={15}/></button>}</div></article>; }
function Dashboard({ items, setDemo, client, refresh }: Workspace) { const open = items.filter(x => !x.resolved); const planning = open.filter(x => x.type === "Planning Update"); const assessments = open.filter(x => x.type === "Assessment"); return <><AdvisorHeader eyebrow="ACTIONABLE FIRST-BUILD VIEWS" title="Good morning, Michael.">Focus on changes, conditions, and follow-up needs across your assigned clients.</AdvisorHeader><section className="advisor-summary"><div><span>Needs attention</span><strong>{open.length}</strong><small>Open client exceptions</small></div><div><span>Planning Updates</span><strong>{planning.length}</strong><small>Due or needing review</small></div><div><span>Assessments</span><strong>{assessments.length}</strong><small>Available for review</small></div><div><span>Follow-up</span><strong>{open.filter(x => x.type === "Follow-up").length}</strong><small>Active conversations</small></div></section><div className="advisor-layout"><section><div className="advisor-section-title"><div><p>PRIORITIZED FOR YOU</p><h2>Needs attention</h2></div><Link to="/advisor/attention">View all <ChevronRight size={15}/></Link></div><div className="advisor-list">{open.slice(0, 3).map(item => <ReviewCard key={item.id} item={item} resolve={id => resolveItem(setDemo, id)}/>)}</div><div className="advisor-section-title split"><div><p>RECENT ACTIVITY</p><h2>Client momentum</h2></div><Link to="/advisor/activity">View activity <ChevronRight size={15}/></Link></div><ActivityRows client={client}/></section><aside className="advisor-rail"><section className="advisor-rail-card"><p>PLANNING UPDATE QUEUE</p><h2>{planning.length} items to consider</h2><span>{client.planning.status === "Completed" ? "Sarah’s update has synced to this workspace." : "Sarah’s update will appear once completed."}</span><Link to="/advisor/planning">Open Planning Updates <ChevronRight size={15}/></Link></section><section className="advisor-rail-card"><p>COMMUNICATIONS</p><h2>1 approval needed</h2><span>Review the reminder before it is released.</span><Link to="/advisor/communications">Review communications <ChevronRight size={15}/></Link></section><section className="advisor-rail-card advisor-client-count"><UsersRound size={22}/><h2>84 assigned clients</h2><span>Only your assigned clients are shown in this prototype.</span><Link to="/advisor/clients">Open client list <ChevronRight size={15}/></Link></section></aside></div><button className="advisor-sync" onClick={refresh}>Refresh local client-demo activity</button></> }
function Attention({ items, setDemo }: Workspace) { const open = items.filter(x => !x.resolved); return <><AdvisorHeader eyebrow="NEEDS ATTENTION" title="Client exceptions, with a reason.">Only activity that needs review is surfaced here. Completing a routine update alone does not automatically create a task.</AdvisorHeader><section className="advisor-filter"><span>{open.length} open exceptions</span><button className="button secondary" onClick={() => setDemo(s => ({ ...s, resolved: [] }))}>Restore demo queue</button></section><div className="advisor-list wide">{open.length ? open.map(item => <ReviewCard key={item.id} item={item} resolve={id => resolveItem(setDemo, id)}/>) : <div className="advisor-empty"><CheckCircle2/><h2>You are up to date.</h2><p>No active client exceptions are waiting for review.</p></div>}</div></> }
function PlanningQueue({ items, setDemo, client }: Workspace) { const list = items.filter(x => x.type === "Planning Update"); return <Queue title="Planning Updates" eyebrow="RECURRING CLIENT UPDATES" description="Review meaningful changes and overdue updates. Routine completions with no material change stay out of the exception queue." items={list} setDemo={setDemo} detail={client.planning.status === "Completed" ? `Sarah Smith submitted a Planning Update${client.planning.changes.length ? ` with ${client.planning.changes.length} detected change(s).` : " with no detected changes."}` : "Sarah Smith’s September Planning Update is due September 30."}/> }
function AssessmentQueue({ items, setDemo, client }: Workspace) { const list = items.filter(x => x.type === "Assessment"); return <Queue title="Assessments" eyebrow="ASSESSMENT REVIEW" description="Review a client’s fixed assessment result when the approved business rule calls for advisor attention." items={list} setDemo={setDemo} detail={client.assessment.status === "Completed" ? `Sarah Smith completed the Investment & Risk Assessment: ${client.assessment.result}.` : "Sarah Smith’s Investment & Risk Assessment is available but not complete."}/> }
function FollowUps({ items, setDemo }: Workspace) { return <Queue title="Follow-up / review" eyebrow="ACTIVE CONVERSATIONS" description="Track focused next steps. This is not a generalized task or workflow system." items={items.filter(x => x.type === "Follow-up")} setDemo={setDemo} detail="A follow-up can come from an approved Planning Update change, assessment review cue, or advisor decision."/> }
function Queue({ title, eyebrow, description, items, setDemo, detail }: { title: string; eyebrow: string; description: string; items: ReviewItem[]; setDemo: React.Dispatch<React.SetStateAction<AdvisorDemo>>; detail: string }) { return <><AdvisorHeader eyebrow={eyebrow} title={title}>{description}</AdvisorHeader><section className="advisor-context"><ClipboardList/><span>{detail}</span></section><div className="advisor-list wide">{items.length ? items.map(item => <ReviewCard key={item.id} item={item} resolve={id => resolveItem(setDemo, id)}/>) : <div className="advisor-empty"><CheckCircle2/><h2>No open items.</h2><p>New qualifying activity will appear here.</p></div>}</div></> }
function Communications({ demo, setDemo }: Workspace) { const approve = (id: string) => setDemo(s => ({ ...s, communications: s.communications.map(x => x.id === id ? { ...x, status: "Ready" } : x) })); return <><AdvisorHeader eyebrow="COMMUNICATIONS" title="Review before release.">Firm settings currently require advisor approval. No messages are sent from this prototype.</AdvisorHeader><section className="advisor-list wide">{demo.communications.map(item => <article className="advisor-review" key={item.id}><div className="advisor-initials">{item.client.split(" ").map(x => x[0]).join("")}</div><div className="advisor-review-main"><span className={`priority priority-${item.status === "Approval needed" ? "high" : "standard"}`}>{item.status}</span><h3>{item.client}</h3><p>{item.subject}</p><small>{item.date}</small></div><div className="advisor-review-action">{item.status === "Approval needed" ? <button className="button secondary" onClick={() => approve(item.id)}>Approve demo message <Check size={15}/></button> : <span><Check size={15}/> Ready</span>}</div></article>)}</section><section className="advisor-context"><Mail/><span>Delivery channel, consent, sender identity, templates, and retention rules are intentionally not implemented in this MVP prototype.</span></section></> }
function ActivityRows({ client }: Pick<Workspace, "client">) { const rows = [...client.history.map(x => ({ text: `Sarah Smith · ${x.title}`, time: "Today" })), { text: "Elise Robinson · Retirement timeline updated", time: "Yesterday" }, { text: "Martin Cole · Assessment reminder prepared", time: "Sep 7" }]; return <section className="activity-rows">{rows.map((row, i) => <div key={`${row.text}-${i}`}><Activity size={17}/><strong>{row.text}</strong><span>{row.time}</span></div>)}</section>; }
function RecentActivity({ client }: Workspace) { return <><AdvisorHeader eyebrow="RECENT ACTIVITY" title="A concise history of client momentum.">Use this view for continuity. Work requiring a decision remains in Needs attention.</AdvisorHeader><ActivityRows client={client}/></> }
function ClientList({ items }: Workspace) { const clients = [{ name: "Sarah Smith", stage: "Approaching retirement", status: items.some(x => x.client === "Sarah Smith" && !x.resolved) ? "Needs attention" : "Current", last: "Today" }, { name: "Elise Robinson", stage: "Approaching retirement", status: "Needs attention", last: "Yesterday" }, { name: "Martin Cole", stage: "Building toward retirement", status: "Assessment review", last: "Sep 7" }, { name: "Ana Morales", stage: "Already retired", status: "Planning Update overdue", last: "Sep 3" }]; return <><AdvisorHeader eyebrow="ASSIGNED CLIENTS" title="Your client list.">Client access in this prototype is limited to Michael Carter’s assigned households.</AdvisorHeader><section className="advisor-client-table"><div className="advisor-client-head"><span>Client</span><span>Life stage</span><span>Current state</span><span>Last activity</span></div>{clients.map(client => <div className="advisor-client-row" key={client.name}><div><span className="advisor-initials small">{client.name.split(" ").map(x => x[0]).join("")}</span><strong>{client.name}</strong></div><span>{client.stage}</span><span>{client.status}</span><span>{client.last}</span></div>)}</section></> }
