export const tenantId='firm-harbor';
export const firm={id:tenantId,name:'Harbor Wealth',communicationMode:'Advisor Approval',features:{planning:true,assessment:true,education:true}};
export const advisor={id:'advisor-michael',tenantId,name:'Michael Carter',credentials:'CFP®',email:'michael@example.com',phone:'+1-202-555-0148'};
export const assignment={id:'relationship-1',tenantId,clientId:'client-sarah',advisorId:advisor.id,status:'Active',isPrimary:true};
export type Profile={name:string;dob:string;stage:string;retirementAge:number;relationship:string;partner:string};
export type Snapshot={retirementAge:number;employment:string;household:string;concern:string};
export type Change={field:keyof Snapshot;before:string;after:string;requiresAttention:boolean};
export type State={version:1;activated:boolean;consentAt?:string;profileComplete:boolean;profile:Profile;baseline:Snapshot;draft:Snapshot;planning:{id:string;tenantId:string;version:string;status:'Due'|'Completed';completedAt?:string;changes:Change[]};assessment:{id:string;tenantId:string;version:string;answers:number[];status:'Available'|'Completed';result?:string;completedAt?:string};exceptions:{id:string;tenantId:string;sourceId:string;reason:string;status:'Open';advisorId:string}[];history:{id:string;title:string;date:string}[];read:string[]};
export function initialState():State {const baseline={retirementAge:65,employment:'Employed full-time',household:'No changes',concern:''};return {version:1,activated:false,profileComplete:false,profile:{name:'Sarah',dob:'1966-11-12',stage:'Approaching retirement',retirementAge:65,relationship:'Married / partnered',partner:'James'},baseline,draft:{...baseline},planning:{id:'update-2026-q3',tenantId,version:'planning-v1',status:'Due',changes:[]},assessment:{id:'risk-2026',tenantId,version:'risk-demo-v1',answers:[],status:'Available'},exceptions:[],history:[],read:[]};}
export function submitPlanning(s:State):State {if(s.planning.status==='Completed')return s;const changes=(Object.keys(s.baseline) as (keyof Snapshot)[]).filter(k=>String(s.baseline[k])!==String(s.draft[k])).map(field=>({field,before:String(s.baseline[field]||'None'),after:String(s.draft[field]||'None'),requiresAttention:true}));const date=new Date().toISOString();return {...s,baseline:{...s.draft},profile:{...s.profile,retirementAge:s.draft.retirementAge},planning:{...s.planning,status:'Completed',completedAt:date,changes},exceptions:changes.length?[...s.exceptions,{id:'exception-planning',tenantId,sourceId:s.planning.id,reason:changes.map(c=>`${c.field}: ${c.before} → ${c.after}`).join('; '),status:'Open',advisorId:advisor.id}]:s.exceptions,history:[{id:s.planning.id,title:changes.length?'Planning Update completed · changes flagged for review':'Planning Update completed · no changes',date},...s.history]};}
export function submitAssessment(s:State):State {if(s.assessment.status==='Completed'||s.assessment.answers.length!==4||[0,1,2,3].some(i=>!Number.isInteger(s.assessment.answers[i])||s.assessment.answers[i]<0||s.assessment.answers[i]>2))return s;const score=s.assessment.answers.reduce((a,b)=>a+b,0);const result=score<=2?'Cautious':score<=5?'Balanced':'Growth-oriented';const date=new Date().toISOString();const requiresReview=result!=='Balanced';return {...s,assessment:{...s.assessment,status:'Completed',result,completedAt:date},exceptions:requiresReview?[...s.exceptions,{id:'exception-assessment',tenantId,sourceId:s.assessment.id,reason:`Investment & Risk Assessment result (${result}) meets the illustrative review rule`,status:'Open',advisorId:advisor.id}]:s.exceptions,history:[{id:s.assessment.id,title:'Investment & Risk Assessment completed',date},...s.history]};}
export function progress(s:State){return Math.round(([s.profileComplete,s.planning.status==='Completed',s.assessment.status==='Completed'].filter(Boolean).length/3)*100)}
